import numpy as np
from numpy import genfromtxt
import scipy
import Image
import matplotlib.pyplot as plt


class VhdlAPI:
    source_bin_file = 'image_0_200x200_pad.min'
    source_bin_path='binaries/'

    def __init__(self, source_bin_path = source_bin_path, source_bin_file = source_bin_file):
        self.source_bin_path = source_bin_path
        self.source_bin_file = source_bin_file

    def bin2vhdl(self):
        source_file = self.source_bin_path + self.source_bin_file
        output_file = self.source_bin_path + str.split(self.source_bin_file,".")[0]+".pad"
        print('Converting to VHDL Binary Format')
        array = genfromtxt(source_file, delimiter=',')
        print(array)
        array[array == 255.0] = 1
        print(array)
        np.savetxt(output_file, array, delimiter=",")

    def vhdlbin2jpg(self,bin_file):
        image_array = genfromtxt(bin_file, delimiter=',')
        output_file = str.split(bin_file, ".")[0] + "_vhdl_crop.jpg"
        # scipy.misc.imsave(output_file, image_array)
        plt.imshow(image_array, cmap=plt.get_cmap('gray'))
        plt.savefig(output_file)

    def remove_single_padding(self, arr):
        row_size = len(arr[0])
        print(row_size)
        a1 = np.delete(arr, 0, axis=1)
        a2 = np.delete(a1, 0, axis=0)
        a3 = np.delete(a2, row_size - 2, axis=0)
        a4 = np.delete(a3, row_size - 2, axis=1)
        return a4

    def vhdlbin2bin(self, source_file):
        # converts the vhdl format bin file to normal bin file generated by opencv
        # data range in vhdl bin is 0 or 1, and opencv is 0 or 255
        image_array = genfromtxt(source_file, delimiter=',')
        unpad_image_array = image_array
        unpad_image_array[unpad_image_array == 1.0] = 255.0
        return unpad_image_array

    def vhdlbinimg2binimg(self, source_file, output_file):
        # converts a vhdlbinaries file to a opencv binarized image
        new_array = self.vhdlbin2bin(source_file)
        arr = np.array(new_array)
        print(arr.shape)
        arr[arr <255 ] = 0.0
        plt.imshow(arr,cmap=plt.get_cmap('gray'))
        plt.savefig('test/cat_vhdlbin2img.jpg')


